각 모델 생성 및 hit_rate 비교
UOUCapstoneDesignTeam/Ulsan_recommandation_Systyem pull request #23
Opened 2023-04-14 11:40 UTC by pass0210

각각의 hit_rate입니다.
모두 K가 15를 넘어가면 같습니다.

# MF
- 10: 0.85
- 15: 0.9856115107913669
- 20: 0.9856115107913669

# NCF_1
- 10: 0.84
- 15: 0.9856115107913669
- 20: 0.9856115107913669

# NCF_2
- 10: 0.83
- 15: 0.9856115107913669
- 20: 0.9856115107913669

# Hybrid_Recysys
- 10: 0.82
- 15: 0.9856115107913669
- 20: 0.9856115107913669

2023-04-14 12:37 UTC, ChangZero reviewed
신경망 모델 중에 가장 성능 줗은 Matrix Factorization 을 import 해서 hybrid 추천시스템에 탑재하심이 좋을 듯합니다 
latent dim (잠재요인)은 100으로 굳이 고정하지 않으셔도 됩니다. 해당 데이터에 맞는 값을 찾으시면 됩니다
하이브리드 추천에서 content결과에 따라 가중치를 더해주는데 이 가중치 또한 데이터에 맞게끔 조절(최적화) 하시면 됩니다

2023-04-14 12:40 UTC, ChangZero requested changes
신경망 모델 중에 가장 성능 줗은 Matrix Factorization 을 import 해서 hybrid 추천시스템에 탑재하심이 좋을 듯합니다
latent dim (잠재요인)은 100으로 굳이 고정하지 않으셔도 됩니다. 해당 데이터에 맞는 값을 찾으시면 됩니다
하이브리드 추천에서 content결과에 따라 가중치를 더해주는데 이 가중치 또한 데이터에 맞게끔 조절(최적화) 하시면 됩니다

2023-04-15 03:53 UTC, pass0210 commented
넵!

2023-04-17 13:11 UTC, pass0210 commented
latent_dim각각 넣었을 때 hit rate

## MF
- 50: .78
- 60: .78
- 70: .79
- 80: .82
- 90: .8
- 100: .8

## NCF_1
- 50: .83
- 60: .84
- 70: .84
- 80: .83
- 90: .81
- 100: .82

## NCF_2
- 50: .84
- 60: .79
- 70: .81
- 80: .83
- 90: .84
- 100: .81

각각 돌려보고 가장 높은 값으로 latent_dim수정하고 하이브리드 모델도 가중치 조절해서 올렸습니다!

2023-04-17 13:20 UTC, ChangZero commented
> 

하이브리드 추천시 Hit rate은 어떻게 나오나요?

2023-04-17 13:33 UTC, pass0210 commented
NCF_2와 동일하게 나옵니다!

2023-04-17 13:35 UTC, ChangZero approved these changes

2023-04-17 13:49 UTC, NAKTA-Y approved these changes

2023-04-17 13:50 UTC, merged